server/server/face_rec/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

server/server/server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import server.settings as settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('face_rec.urls', namespace="face_rec")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/face_rec/models.py
from django.db import models
from django.core.files import File

import os

class TrainImage(models.Model):
	image = models.ImageField(upload_to="train/")

	label = models.ForeignKey("Label")

	def __str__(self):
		return self.label.name

class Label(models.Model):
	name = models.CharField(max_length = 100)

	def __str__(self):
		return self.name

class TestImage(models.Model):
	orig_img = models.ImageField(upload_to="test/", null=True)
	face_img = models.ImageField(upload_to="test/", null=True)

	has_face = models.BooleanField(default=False)
	has_modi = models.BooleanField(default=False)
	has_kejr = models.BooleanField(default=False)

server/server/face_rec/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files import File

from .models import TestImage
import face_rec.recognizer as recognizer


import os

def index(request):
	if request.method == "POST" and request.FILES["image"]:
		test_img = TestImage()
		test_img.orig_img = request.FILES["image"] 		

		test_img.save()

		has_face = do_face_detect(test_img)

		if has_face:
			do_face_rec(test_img)

		return render(request, "result.html", {"image": test_img})


	return render(request, "index.html", {})


def do_face_detect(test_img):
	basedir = os.path.dirname(test_img.orig_img.path)
	basename = os.path.basename(test_img.orig_img.path)

	face_path, faces = recognizer.face_detect(basename, basedir)

	test_img.has_face = faces
	test_img.face_img = File(open(face_path, "rb"))

	test_img.save()

	return faces

# Modi == 1
# Kejr == 2
def do_face_rec(test_img):
	labels, confs = recognizer.face_rec(test_img.orig_img.path)

	for label, conf in zip(labels, confs):
		if conf < 100:
			if label == 1:
				test_img.has_modi = True

			if label == 2:
				test_img.has_kejr = True

	test_img.save()

	pass

server/server/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>PreCog Task B</title>
</head>
<body>
	<form action="{% url 'face_rec:index' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="file" name="image">
		<br>
		<input type="submit" name="">
	</form>
</body>
</html>

server/server/templates/result.html
<!DOCTYPE html>
<html>
<head>
	<title>PreCog Task B</title>
</head>
<body>
	<table>
		<tr>
			<td>Face Present: </td>
			<td>{{ image.has_face }}</td>
		</tr>
		<tr>
			<td>Narendra Modi:</td>
			<td>{{ image.has_modi }}</td>
		</tr>
		<tr>
			<td>Arvind Kejriwal: </td>
			<td>{{ image.has_kejr }}</td>
		</tr>
	</table>

	<br>
	<img src="{{image.face_img.url}}">
</body>
</html>